### ISSUE TITLE
Can't run Express

### ISSUE THREAD

**Issue by paperref** [MineralsCloud/Express.jl#232]
Hi,
I'm one of the referees for your paper. I've received the scripts you sent me through the editor and ran them (I'm using julia1.6 to run your code though). I'm then trying to run an `eos` calculation shown here:
![image](https://user-images.githubusercontent.com/111350673/184849527-4a705841-bcd6-457d-bf06-23b0f6d8584c.png)

If I run it using `xps` I get this error:
![image](https://user-images.githubusercontent.com/111350673/184849220-3aa36c5e-d81b-4c6e-8c91-abe57c8c70cb.png)

When trying to run it with a julia script I run into a different error:
![image](https://user-images.githubusercontent.com/111350673/184849699-a8dc1eea-2cec-4c65-b6fd-778529a66533.png)
![image](https://user-images.githubusercontent.com/111350673/184849856-cc590235-6035-4168-ad74-42f46cb2d54e.png)

Any ideas on how to fix this?

**Comment by singularitti** [comment]
Dear referee, hi! It is nice to talk to you in this way. Yes, I am well aware of this issue. It is related to how we save the tracked status of the `Workflow`. 
Is it possible that you were rerunning a workflow with an already saved file in the same directory (It probably has the name `status.jls` or `status.jld2`,)? The first screenshot is probably because you have a `status.jls` file but running with the latest version of code (where we shifted to the `JLD2` file format recently.)?
The second screenshot is caused by the similar reason, and I am aware of that. It is because we cannot save some Julia data structures to file and reload them. See [issue 133](https://github.com/MineralsCloud/SimpleWorkflows.jl/issues/133) and [issue 134](https://github.com/MineralsCloud/SimpleWorkflows.jl/issues/134).
Unfortunately, I am not able to solve issue 134 immediately since it is a Julia language issue, and it is beyond my capability. I [have tried several different solutions](https://github.com/MineralsCloud/SimpleWorkflows.jl/issues/134#issuecomment-1214970790), but each of them has some drawbacks. But it might be simpler than I thought in the end. Anyway, I am trying my best to solve this issue.
To solve your problem temporarily, could you try deleting any `.jls` or `.jld2` file and retry?

**Comment by paperref** [comment]
Hi,
Yea JLD2 is sometimes not the most reliable I have found. Maybe just using JSON with JSON3 or BSON would be an option?
In any case, it seems that the code is somewhat running, but now I have a load of other errors that appear from within Unitful I think:
![image](https://user-images.githubusercontent.com/111350673/185807665-1270b669-3a1c-433f-8a29-dd686b6ca0d2.png)

**Comment by singularitti** [comment]
Dear referee, hi! Good news to hear it is finally running! Yes, `JLD2` was not so smooth to use. I am not sure I can use a JSON format (with `JSON.jl` or `JSON3.jl`) to store the workflow status file since I am storing binary data here (functions, etc.). So it might not be able to be stored in human-readable formats. BSON is a possible format, but as I said, [it is still not perfect](https://github.com/MineralsCloud/SimpleWorkflows.jl/issues/134#issuecomment-1214970790). I will keep trying anyway.

For your screenshot, could you tell me what is `57.84 GPa` and `8.0` here? I guess `57.84 GPa` is the bulk modulus at 0 GPa and 8.0 is its derivative?

**Comment by louisponet** [comment]
Oh you're trying to store functions? Yea that won't work for sure,I've tried that before and since they are tightly bound to the generating process (world age, other functions defined, packages loaded, etc) I don't think that can ever work.

To be honest I'm not sure where those numbers come from, I'm just running the eos example from the documentation. I can try running it using a different template?

**Comment by paperref** [comment]
Hi,

Oh no I don't think you can ever store functions in a JLD2 since they are very tied to the generating environment, i.e. they heavily depend on the loaded modules, which other functions were already defined, world age etc. I've tried this before and it simply doesn't work afaik. 

Back to the numbers, I honestly don't know where they come from, I'm just running the eos.yaml configuration from the documentation, I think these are generated somewhere inside your code.

**Comment by paperref** [comment]
> Could you please show me your eos.yaml?

It is shown in the screenshot of the first post here.

**Comment by singularitti** [comment]
Dear referee, hi. I have never met such an error before. Could you show a little bit more of your screenshot? Is it `p=5.0` or `p=-5.0` has this error? I do not have any `57.84 GPa` or `8.0` in my code. So I guess it could be when the code is finding zeros of an equation of state, it came across some hidden bug (probably not in my code). I am updating the code to let it show more direct and precise error messages, stay tuned!

**Comment by paperref** [comment]
I’ve just tried with a different template file for the pw calculation and same result. I’m sure it’s not that there’s any number like that somewhere in your code, but it’s probably from parsing or something similar? I don’t see any output files being produced so I’m not even sure if it runs anything to begin with. I tried running the template itself and that all seems to work. Not clear what’s going on here

**Comment by volkerblum** [comment]
This sounds to me like a bug in one version of Unitful that is not present in another. Can each of you please post the versions of Unitful that you are using so that we can compare notes? That would be very helpful. Thank you!

**Comment by paperref** [comment]
My Manifest.toml looks like the attached:
[Manifest.txt](https://github.com/MineralsCloud/Express.jl/files/9417392/Manifest.txt)

**Comment by volkerblum** [comment]
So version 1.11.0, right? That looks current.

https://github.com/PainterQubits/Unitful.jl/tags

@singularitti - what version are you using?

**Comment by singularitti** [comment]
> So Unitful version 1.11.0, right? That looks current.
> 
> https://github.com/PainterQubits/Unitful.jl/tags
> 
> @singularitti - what version are you using?

Dear Dr. Blum @volkerblum and referee @paperref,
Hi. I am using version 1.11.0, too. Here is my [Manifest.toml](https://pastebin.com/eBkyKvD0). I have compared mine and the referee's, the only noticeable differences are the following packages:

```julia
 "FillArrays"
 "ArnoldiMethod"
```

They correspond to [`FillArrays.jl`](https://github.com/JuliaArrays/FillArrays.jl) and [`ArnoldiMethod.jl`](https://github.com/JuliaLinearAlgebra/ArnoldiMethod.jl), which are pretty standard Julia libraries. So I do not think there should be a big difference between our dependencies. However, I do notice that my [`Manifest.toml`](https://pastebin.com/eBkyKvD0) only has 165 entries, and the referee's [`Manifest.toml`](https://github.com/MineralsCloud/Express.jl/files/9417392/Manifest.txt) has 270 entries. There still exists a slim chance that their packages have more tricky dependencies that could cause this error.

I am pasting my Manifest.toml [here](https://pastebin.com/eBkyKvD0), if the referees want to compare, they can use the following code:

```julia
using Pkg.TOML
mine = TOML.parsefile("/path/to/referees/Manifest.toml")  # All the packages that I installed
theirs = TOML.parsefile("/path/to/authors/Manifest.toml")  # All the packages that they installed
setdiff(mine, theirs)  # Construct the set of elements in `mine` but not in `theirs`
setdiff(theirs, mine)  # Construct the set of elements in `theirs` but not in `mine`
```

After all, I am considering this is not a problem of `Unitful.jl`. This is probably a problem with the "finding-zero algorithm" in [`Roots.jl`](https://juliamath.github.io/Roots.jl/dev/reference/#Roots.find_zero). Since [in my code](https://github.com/MineralsCloud/EquationsOfStateOfSolids.jl/blob/8cf4e143e0770c37b9765d657904418fa1fa6de3/src/vsolve.jl#L119-L147), I was solving $P = P(V)$ backwards: $P(V|_{V_i}) = P_i$ to find $V_i$ from a given equation of state. I guess it is when $P = -5 GPa$ or $P = 5 GPa$ have some problem with that. I have never seen such an error before in my tests.

**Comment by singularitti** [comment]
Dear Dr. Blum @volkerblum and referee @paperref,
I think I knew where does the bug come from. It should be [in this line](https://github.com/MineralsCloud/EquationsOfStateOfSolids.jl/blob/8cf4e143e0770c37b9765d657904418fa1fa6de3/src/vsolve.jl#L134). In [the example](https://github.com/MineralsCloud/QuantumESPRESSOExpress.jl/blob/30cf6cc25ca00a1e118adc9b1951e3772c09a095/examples/Ge/eos.yaml#L25), the equation of state's $B'_0 = 4.82$, when timed by $12$, it is $57.84$, and that is where $57.84 - 8.0$ come from. However, $4.82$ is unitless, I am not sure why it suddenly has a unit of `GPa`. Is it possible that the referee changes `eos.yaml` or something happens so that the file is wrongly parsed and the `GPa` was added to `4.82`? This thing could happen, please see [one of my troubleshooting suggestions](https://mineralscloud.github.io/Express.jl/stable/troubleshooting/#Error-parsing-YAML-files).

**Comment by volkerblum** [comment]
eos.yaml is shown as a screenshot in the first comment, I think. Should it look that way? Note that it says "4.82 GPa". Can you (@singularitti ) reproduce that bug if you have that line? 
Also, I believe @paperref mentioned that this is the eos.yaml file from the documentation. 
Is the "GPa" unit shown in the first eos.yaml screenshot in the documentation?

**Comment by singularitti** [comment]
Dear Dr. Blum @volkerblum and referee @paperref,
I believe the error is from the "4.82 GPa" line. I am sorry I did not notice this line when the error was reported, so it took days for me to understand this error. The `eos.yaml` [from the doc looks like this](https://mineralscloud.github.io/Express.jl/dev/run/configuration/):

```yaml
recipe: eos
cli:
  mpi:
    np: 16
template: template.in
save:
  status: status.jld2
fixed:
  pressures:
    unit: GPa
    values:
      - -5
      - -2
      - 0
      - 5
      - 10
      - 15
      - 17
      - 20
trial_eos:
  type: bm3
  values:
    - 300.44 bohr^3
    - 74.88 GPa
    - 4.82
  ```

There is no "GPa" after "4.82". I suppose the referee accidentally added it?

From the referee's configuration file I guess he/she was testing on NiO? While the parameters in our equation of state ($V_0 = 300.44$ bohr^3, $B_0 = 74.88$ GPa, $B'_0 = 4.82$) from our [documentation](https://mineralscloud.github.io/Express.jl/dev/run/configuration/) is for metal Germanium. I am not sure these parameters are a good starting guess since they are of different structures. It still might be optimizable, but a bad guess would slow down the calculations and sometimes even fail to find the volume for the corresponding pressure. We suggest referencing the related publication results as the starting point of these parameters.

**Comment by paperref** [comment]
Oh I see, I will try without the GPa 🤞

**Comment by paperref** [comment]
Cool, it seems to be running now. Fantastic. So I’d say all is fine, but I think it would be highly useful if you implement a bit more checks and error handling so that it’s more clear what’s going on. And also something to add export statements such as `export OMP_NUM_THREADS=1` etc (although I guess the idea is that you’d do that before running Express in the shell?). And the saved.jld2 issue. But aside from that all clear for me!

**Comment by singularitti** [comment]
Dear referee,
Great to hear it works!

> it would be highly useful if you implement a bit more checks and error handling so that it’s more clear what’s going on

Yes, I am working on adding more checks & error tracking things (e.g., instead of only saving a bare `Exception` type, now we save the [entire stack trace also](https://github.com/MineralsCloud/SimpleWorkflows.jl/pull/147/files) to know where exactly the error was thrown). More checks like type checking and value checking will be added, too. The entire codebase is iterating very fast.

> And also something to add export statements such as export OMP_NUM_THREADS=1 etc (although I guess the idea is that you’d do that before running Express in the shell?)

Indeed, I do have the environment variable exported in my shell. I do not like dealing with environment variables in Julia because that might break the users' environment. But I can add a documentation item on the troubleshooting page.

> the saved.jld2 issue

To solve this, I just worked out [a new version](https://github.com/MineralsCloud/SimpleWorkflows.jl/releases/tag/v0.18.0) issue. I found that instead of saving it as `JLD2` files, I need to save it in `.jls` files, which can store anonymous functions with keywords. I will try to test it a few times later today, and hopefully, it will be solved completely.

**Comment by paperref** [comment]
> I need to save it as .jls files, which can store anonymous functions with keywords.

Oh really, that’s interesting, I thought it was pretty much never possible to store functions. I used to generate their sourcecode using `code_string` from CodeTracking.jl. 

Anyhow if it works it works and that’s great. I’ll submit a positive final decision for your paper. It was a long road but we got there in the end!
